In [1]:
import midii

import preprocess_svs as ps
from preprocess_svs.feature import extract_features

In [2]:
preprocessed_gv_path = 'preprocessed_gv/'
preprocessed_mssv_path = 'preprocessed_mssv/'
preprocessed_gv_wav_path = 'preprocessed_gv/wav/'
preprocessed_mssv_wav_path = 'preprocessed_mssv/wav/'

In [3]:
preprocessed_gv_wav_paths = list(ps.get_files(preprocessed_gv_wav_path, 'wav'))

In [4]:
extracted_wav_sample = ps.read_wav(preprocessed_gv_wav_paths[0], normalize=True)

In [5]:
f0, mel, energy = extract_features(extracted_wav_sample, sampling_rate=midii.DEFAULT_SAMPLING_RATE, n_fft=1024, win_length=1024, hop_length=256)

c:\Users\chans\repo\preprocess-SVS\.venv\Lib\site-packages\torch\functional.py:730: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\SpectralOps.cpp:880.)
  return _VF.stft(  # type: ignore[attr-defined]


In [6]:
f0, type(f0)

(array([0., 0., 0., ..., 0., 0., 0.], shape=(1790,)), numpy.ndarray)

In [7]:
mel, type(mel)

(tensor([[-7.1479, -6.9183, -7.3070,  ..., -5.6466, -6.0739, -6.3339],
         [-6.6667, -6.5631, -7.3743,  ..., -3.8350, -4.1891, -4.6045],
         [-7.0662, -7.0467, -7.5311,  ..., -4.6471, -4.8273, -5.2363],
         ...,
         [-6.2536, -5.7514, -5.5927,  ..., -9.1766, -7.3946, -7.3396],
         [-6.3146, -6.3833, -6.2514,  ..., -9.0955, -7.2765, -7.2206],
         [-6.6077, -6.6036, -6.3471,  ..., -9.4065, -7.6264, -7.5520]]),
 torch.Tensor)

In [8]:
energy, type(energy)

(tensor([3.1426, 3.4497, 4.3272,  ..., 0.7822, 1.0256, 1.1691]), torch.Tensor)

In [9]:
ps.save_f0_mel_energy(preprocessed_gv_wav_paths[0], preprocessed_gv_path)

In [10]:
ps.save_all_f0_mel_energy(preprocessed_gv_wav_path, preprocessed_gv_path)